# Generated by Django 2.2.1 on 2019-05-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
        ('atividade', '0001_initial'),
        ('endereco', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atividade',
            field=models.ManyToManyField(to='atividade.Atividade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='presenca',
            field=models.ManyToManyField(to='presenca.Presenca'),
        ),
    ]
