# Generated by Django 2.2.1 on 2019-05-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190511_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programadores', models.CharField(max_length=250)),
                ('gitHub', models.CharField(max_length=200)),
                ('desricao', models.CharField(max_length=200)),
                ('versaoDaAPI', models.CharField(max_length=20)),
                ('versaoDoApp', models.CharField(max_length=20)),
                ('dataDeCriacao', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='presenca',
            field=models.ManyToManyField(to='presenca.Presenca'),
        ),
    ]
